name: pre-commit

on:
  pull_request:
  push:
    branches:
     - main

jobs:
  pre-commit:
    runs-on: aaaaaaubuntu-latestxrx
    strategy:
      fail-fast: true
      matrix:
        python-version: [ "3.10.8" ]
    steps:
      - name: clones the code
        uses: actions/checkout@v3
      - name: installs python
        uses: actions/setup-python@v3
        with:
          python-version: "${{ matrix.python-version }}"
      - name: sets up the pre-commit cache
        uses: pre-commit/action@v3.0.0
